### ISSUE TITLE
Enable control for changing opacity of superpixel boundaries

### ISSUE THREAD

**Issue by jeffbaumes** [DigitalSlideArchive/wsi-superpixel-guided-labeling#10]

**Comment by bnmajor** [comment]
Added in #77 and improved in #84.

**Comment by jagstein** [comment]
Sueprpixel boundaries are not displaying in the latest update (as of 3/8/24), nor are superpixels interactable. I cannot label.

![Image](https://github.com/DigitalSlideArchive/wsi-superpixel-guided-labeling/assets/6061875/338f1c8f-1875-4803-8638-82ae7510f31b)

**Comment by bnmajor** [comment]
@jagstein I am going to open a new issue for this to make it easier for me to monitor (I often lose track of these threads that are in closed issues, sorry).
