### ISSUE TITLE
We need a small css tweak to handle certain certainty values

### ISSUE THREAD

**Issue by bnmajor** [DigitalSlideArchive/wsi-superpixel-guided-labeling#136]
We need a small css tweak to handle certain certainty values:
![image](https://github.com/user-attachments/assets/8d7f0423-7f00-4a60-b293-755e403e3728)
(it could be on a different PR)

_Originally posted by @manthey in https://github.com/DigitalSlideArchive/wsi-superpixel-guided-labeling/issues/130#issuecomment-2296756740_

**Comment by manthey** [comment]
Apparently I already created issue #133 to track this but I had forgotten that I did so.

**Comment by bnmajor** [comment]
Thanks @manthey I completely missed that
