### ISSUE TITLE
Reset chip index after retraining

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/wsi-superpixel-guided-labeling#137]
After retraining, if displaying the guided mode (or the next time the guided mode is displayed), we should be focused on the least certain superpixel.  Currently, the position is remembered, so if we have labelled a hundred superpixels, we will be labelling the hundredth least certain superpixel after retraining rather than the first least certain one.

**Comment by bnmajor** [comment]
Fixed in #140
