### ISSUE TITLE
Synchronize active learning categories with folder group yaml file

### ISSUE THREAD

**Issue by naglepuff** [DigitalSlideArchive/wsi-superpixel-guided-labeling#22]
Since there's nothing stopping users from opening up pixelmap annotations from active learning jobs in Histomics and editing them as they please, we can't guarantee what the `categories` property of the pixelmap elements actually looks like. A user could label a superpixel with an arbitrary category, and then the active learning model will add that new category to the set of possible labels.

We can exercise more control over these annotations by establishing some source of truth, such as the folder-level config file (see the documentation [here](https://github.com/DigitalSlideArchive/HistomicsUI/blob/master/docs/config_options.rst)).

The active learning plugin should use this file to synchronize categories of annotations, and remove labels that don't correspond to the defined categories.

**Comment by naglepuff** [comment]
I've given this issue some more thought, and I'm not sure what the best/most intuitive behavior would be. The goal is to make sure all of the superpixel annotations used to active learning have consistent categories, but I'm not sure what the best way to do this is.

The easiest case is when superpixels have just been generated, and there are no labels or predictions. We can use the groups defined in the `.histomicsui_config.yaml` as the categories for that first round of labels.

It gets harder to reason when training is already underway, and either 1) the categories defined in the config file have changed or 2) the most recent label or prediction annotation was changed, e.g. in HistomicsUI.

One option, which would probably be the most consistent, is to use the groups defined in the config file and only those. This would mean editing the label and prediction annotations to be in line with what is defined in the file. This might nuke some predictions and labels if a category exists on the annotations but not in the config file. Is this an acceptable outcome? What are the implications of removing a label category? How would that affect which superpixels we show on the guided labeling interface? 

Another option would be to edit the config file based on all categories that exist in all of the most recent label/prediction annotations across the dataset. This has the advantage of not dropping and labels or predictions, but has to disadvantages of being less consistent (it could bring in distracting categories if some annotations were edited elsewhere), and much slower if we can't load all of the annotations at once.

Both of these approaches add overhead to loading the UI, since we have to process all of the annotations. 

@manthey I think the second approach makes the most sense, since we don't have to nuke any existing predictions, but it does mean it would be impossible to "delete" a category for now

**Comment by manthey** [comment]
These are thoughts in progress:

I don't think deleting a category once they are created is something we should try to support.  Functionally, it would have to unlabel any superpixels labelled with that label.

Maybe the workflow is that if the yaml file exists, it determines the categories and colors for a new training task.  When we perform the first training (or later, if we allow adding new label groups), we save the config file to the local folder, overwriting an existing one.

If there is a folder tree, then there can be a parent yaml file that dictates the proposed starting groups.  In later stages, the offered groups are the union of those that are in the various annotations and those listed in the yaml file.  As you edit things, it would update the current folder to the current set.

**Comment by jagstein** [comment]
Relevant to this -- I did a spate of active learning with marker / tissue / glass as markers.  1st epoch of active learning was fine. During 2nd epoch of active learning, all the other categories on the server appear: 


![Image](https://github.com/DigitalSlideArchive/wsi-superpixel-guided-labeling/assets/6061875/be4ee44d-37d1-449c-8ac5-3d0d2a9e3de1)

Presumably limiting the categories that are allowed within a folder group will solve this issue.

**Comment by manthey** [comment]
I failed to reproduce this in my first go.  I have my two projects in different folders in the Active Learning collection.  Do you have the two sets of images in different folders?  We might need to see the item/folder layout in Girder to figure out how to reproduce.

**Comment by jagstein** [comment]
Three projects, three folders. Here is the item in girder:


![Image](https://github.com/DigitalSlideArchive/wsi-superpixel-guided-labeling/assets/6061875/9fdde7e6-ea6d-437e-861b-b51f1b2765f1)

The extraneous labels didn't appear until 2nd or 3rd round of superpixel classification.

**Comment by bnmajor** [comment]
Resolved in #81. If there are further improvements needed we can create new issues for them.
