### ISSUE TITLE
Clarify that a job is running

### ISSUE THREAD

**Issue by naglepuff** [DigitalSlideArchive/wsi-superpixel-guided-labeling#28]
In addition to the spinner, it may be useful to add a message to explain why the spinner is up. It could also tell users that active jobs can be monitored from the admin console.

**Comment by cooperlab** [comment]
Related to Issue #40 .

**Comment by manthey** [comment]
This may be helped by https://github.com/DigitalSlideArchive/superpixel-classification/pull/6
