### ISSUE TITLE
Labeled count not updating properly

### ISSUE THREAD

**Issue by naglepuff** [DigitalSlideArchive/wsi-superpixel-guided-labeling#32]
If I'm overriding existing labels with a new label, the count for the existing label doesn't decrease as it should. Additionally, it takes 2 clicks to do this, when intuitively it should only take 1.

**Comment by jagstein** [comment]
![Image](https://github.com/DigitalSlideArchive/wsi-superpixel-guided-labeling/assets/6061875/8ff661cb-156c-4048-b78a-9a6b03ecc2fe)

New issue here --> My labeled patch count says these are all infarcts, but they are still colored as though they are marker. I can't get training to work and I can't look at the slides in histomicsUI, so I don't know what label is represented internally
