### ISSUE TITLE
Debounce saves during initial category labelling

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/wsi-superpixel-guided-labeling#46]
I notice that when labelling initial categories, each click results in a save.  If you click quickly, this can end up with a backlog which is apparent when panning and scrolling, as tiles are slower to load.  Ideally, this should be debounced.

**Comment by naglepuff** [comment]
https://github.com/DigitalSlideArchive/wsi-superpixel-guided-labeling/blob/4b92b3bceb282b2eec520ee316183de056878de7/wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialLabels.vue#L124-L126

https://github.com/DigitalSlideArchive/wsi-superpixel-guided-labeling/blob/4b92b3bceb282b2eec520ee316183de056878de7/wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialLabels.vue#L261-L269

It should already be debounced. I can increase the wait time. What do you think would be a reasonable number, 1000ms?
