### ISSUE TITLE
Add Bayesian model with BatchBALD sorting to the superpixel-classification plugin

### ISSUE THREAD

**Issue by naglepuff** [DigitalSlideArchive/wsi-superpixel-guided-labeling#67]
@Leengit @manthey 

This may require changes to [DigitalSlideArchive/superpixel-classification](https://github.com/DigitalSlideArchive/superpixel-classification) and [DigitalSlideArchive/ALBench](https://github.com/DigitalSlideArchive/ALBench)

Ranking superpixels to label by confidence alone is insufficient, as the superpixels with low confidence could be unhelpful to label, for example if they contain some artifacts.

**Comment by Leengit** [comment]
Much of the work will need to be done in the [DigitalSlideArchive/superpixel-classification](https://github.com/DigitalSlideArchive/superpixel-classification) repository.  I have started that work and will note that pull request here once it is created.

**Comment by bnmajor** [comment]
@Leengit I believe this is complete as of DigitalSlideArchive/superpixel-classification#16, correct?
