### ISSUE TITLE
Forward and back chip buttons don't switch image

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/wsi-superpixel-guided-labeling#86]
On a multi-image project, click on another chip properly switches to the appropriate image and shows the relevant bounding box.  The `<-` and `->` buttons show the next set of chips and select the last/first chip and show a bounding box, but don't switch images, so this bounding box can be wrong (including off the image).

**Comment by jagstein** [comment]
Problem in active labeling:
. Chips aren't showing superpixel
. Slide level view doesn't outline superpixel

![Image](https://github.com/DigitalSlideArchive/wsi-superpixel-guided-labeling/assets/6061875/ff79020f-9a38-466b-ac6a-241c484da55e)
