### ISSUE TITLE
Generate 1-2 new streamlined UI options for filmstrip view

### ISSUE THREAD

**Issue by bnmajor** [DigitalSlideArchive/wsi-superpixel-guided-labeling#92]
The "agree" radio buttons are not needed. We should investigate better ways to handle approving/changing/skipping a prediction.

May be related to #64

**Comment by bnmajor** [comment]
@cooperlab @jagstein @manthey @jeffbaumes

I have a few ideas for dropping the "agree - yes / no" radio buttons. The common traits across all are:
1. The drop-down menu is always shown
2. The drop-down menu now has a `No Selection` choice (or some variation of that wording) which is the equivalent of resetting the selection.
3. If the user agrees with the prediction the selection text is emphasized in some way.

Some additional options:
1. "Agree" alternatives
    1. We can replace the radio buttons with a checkbox. Checking the box automatically selects the label matching the prediction from the drop-down menu (and applies any text emphasis we decide is appropriate).
    2. We can remove the radio button but not add the checkbox. The user will have to use a hotkey or the drop-down menu to select the class.
2. Text emphasis
    1. Italicize the `No Selection` option to emphasize that no choice has been made.
    2. Bold the selection when it matches the prediction
    3. Color and thicken the selector border once a user has made a selection - red for "disagree", green for "agree"

Examples:

1. ![Image](https://github.com/DigitalSlideArchive/wsi-superpixel-guided-labeling/assets/51238406/0f309dc8-7ace-4a14-aa12-c734379af431)
2. ![Image](https://github.com/DigitalSlideArchive/wsi-superpixel-guided-labeling/assets/51238406/0d43278f-5d7c-4400-854e-c3e8964a811c)
3. ![Image](https://github.com/DigitalSlideArchive/wsi-superpixel-guided-labeling/assets/51238406/b2b5c347-0677-4e1c-8564-a9d8dcfe0475)

Any combination of ideas would be fine of course. My personal preference is for example number 3, with the option of including the checkbox if users are not using hotkeys and want a faster way to agree with predictions. The checkbox could also be moved below the drop-down menu if it seems useful to keep but less likely to be used than the menu.

**Comment by jeffbaumes** [comment]
I like the idea of not having the checkbox, so choices 2 or 3. IMO since we are using colors for category on the main view, we shouldn't try to also use color to indicate matching prediction. So I have a slight preference for option 2 but we should get input from Jeff G.

**Comment by jagstein** [comment]
I think Jeff B has it.

**Comment by bnmajor** [comment]
Closing as completed in #99
